# Generated by Django 4.2 on 2023-06-23 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Вместимость')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название машины')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('main_photo', models.ImageField(upload_to='photo/%Y/%m/%d/', verbose_name='Фото cо стороны')),
                ('inside_photo_one', models.ImageField(upload_to='photo/%Y/%m/%d/', verbose_name='Первое фото внутри')),
                ('inside_photo_two', models.ImageField(upload_to='photo/%Y/%m/%d/', verbose_name='Второе фото внутри')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('gasoline', models.IntegerField(verbose_name='Обьем топливного бака')),
                ('rent_count', models.IntegerField(verbose_name='Количество аренд')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('capacity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.capacity', verbose_name='Вместимость')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Steering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Двигатель')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=300, verbose_name='Review text')),
                ('review_time', models.DateTimeField(auto_now_add=True, verbose_name='Review data and time')),
                ('review_score', models.IntegerField(choices=[(1, 'Bad'), (2, 'So So'), (3, 'Normal'), (4, 'Nice'), (5, 'Perfect')], verbose_name='Review score')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.car', verbose_name='Car')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User name')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('adress', models.CharField(max_length=100, verbose_name='Adress')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('pick_up_city', models.CharField(max_length=20, verbose_name='Pick-up location')),
                ('pick_up_date', models.DateField(max_length=50, verbose_name='Pick-up date')),
                ('pick_up_time', models.TimeField(max_length=50, verbose_name='Pick-up time')),
                ('drop_off_city', models.CharField(max_length=20, verbose_name='Drop-off location')),
                ('drop_off_date', models.DateField(max_length=50, verbose_name='Drop-off date')),
                ('drop_off_time', models.TimeField(max_length=50, verbose_name='Drop-off time')),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('In progress', 'In progress'), ('Waiting for you', 'Waiting for you'), ('Decline', 'Decline'), ('Check your order', 'Checking your order')], default='Check your order', max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.car', verbose_name='Car')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User name')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.steering', verbose_name='Двигатель'),
        ),
    ]
