# Generated by Django 4.2 on 2023-08-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='text',
            field=models.CharField(max_length=1500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='car',
            name='inside_photo_one',
            field=models.ImageField(upload_to='', verbose_name='Первое фото внутри'),
        ),
        migrations.AlterField(
            model_name='car',
            name='inside_photo_two',
            field=models.ImageField(upload_to='', verbose_name='Второе фото внутри'),
        ),
        migrations.AlterField(
            model_name='car',
            name='main_photo',
            field=models.ImageField(upload_to='', verbose_name='Фото cо стороны'),
        ),
    ]
